# Generated by Django 3.0 on 2024-03-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20240306_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address'},
        ),
    ]
