version: 2.1

executors:
  docker-executor:
    docker:
      - image: barbealexiane07531/p13:latest

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker
          command: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get -y install docker-ce
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: echo "this is the build job"
    # test:
#   docker:
#     - image: barbealexiane07531/oc-lettings-p13:latest
#   steps:
#     - checkout
#     - run: echo "this is the test job"

workflows:
  build_and_test:
    jobs:
      - build
      # - test
