version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.10.2

jobs:
  setup:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
  build:
    executor: docker-executor
    steps:
      - checkout
      - run: echo "this is the build job"
  build-docker-push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Remove old Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker rmi $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest || true
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker tag $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CIRCLE_SHA1 $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CIRCLE_SHA1
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - run:
          name: Login to Azure
          command: |
            echo $AZURE_PASSWORD | az login -u $AZURE_USERNAME --password-stdin
      - run:
          name: Login to Azure Container Registry
          command: |
            az acr login --name $ACR_NAME
      - run:
          name: Tag Docker image
          command: |
            docker tag $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest $ACR_NAME.azurecr.io/$DOCKERHUB_REPO:latest
      - run:
          name: Push Docker image to Azure Container Registry
          command: |
            docker push $ACR_NAME.azurecr.io/$DOCKERHUB_REPO:latest
      - run:
          name: Deploy to Azure Container Instances
          command: |
            az container create --resource-group $RESOURCE_GROUP --name $ACI_NAME --image $ACR_NAME.azurecr.io/$DOCKERHUB_REPO:latest --dns-name-label $ACI_NAME --ports 80

workflows:
  build_and_test:
    jobs:
      - setup
      - build
      - build-docker-push:
          context: docker-context
