version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.10.2

jobs:
  setup:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
  build:
    executor: docker-executor
    steps:
      - checkout
      - run: echo "this is the build job"
  build-docker-push:
    executor: docker-executor

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Remove old Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker rmi $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest || true
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker tag $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CIRCLE_SHA1 $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CIRCLE_SHA1
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest

workflows:
  build_and_test:
    jobs:
      - setup
      - build
      - build-docker-push:
          context: docker-context
