version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.7

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run: echo "this is the build job"
  build-docker-push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker tag $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CIRCLE_SHA1 $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CIRCLE_SHA1
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest

workflows:
  build_and_test:
    jobs:
      - setup
      - build
      - build-docker-push
