version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.7

jobs:
  setup:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker
          command: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get -y install docker-ce
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
  build:
    executor: docker-executor
    steps:
      - checkout
      - run: echo "this is the build job"
  build-docker-push:
    docker:
      - image: barbealexiane07531/oc-lettings-p13:latest/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
            docker tag $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1 $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest
            docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1
            docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest

workflows:
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - build-docker-push:
          requires:
            - build
