name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./python-oc-lettings-fr

      - name: Run Django tests
        run: |
          python3 manage.py test
        working-directory: ./python-oc-lettings-fr
        if: ${{ github.ref == 'refs/heads/tests' }}

      - name: Collect static files
        run: |
          python3 manage.py collectstatic --noinput
        working-directory: ./python-oc-lettings-fr

      - name: Build Docker image
        run: |
          docker build -t HolidayHomes .
          docker tag HolidayHomes barbealexiane07531/HolidayHomes
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Push Docker image to registry
        run: |
          docker push barbealexiane07531/HolidayHomes
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "HolidayHomes"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
        if: ${{ github.ref == 'refs/heads/master' }}
